### PR TITLE
Chore/cleanup eslint

### PR DESCRIPTION
**Pull request by jeswr**
Solves eslint versioning issues I discovered when trying to `npm i` (before realising it was a yarn package setup). It makes use of eslint cleaner by using rushtack and Inrupts default configs to avoid needing to having eslint plugins as dependencies. Mostly similar style to @rubensworks configs except now `"` is enforced instead of `'` as well which is what is causing the large diff.

I've also upgraded most of the package deps at the same time.

### CODE REVIEW

**Comment by rubensworks** [comment]
Thanks for the PR @jeswr!

Was there a particular reason to migrate to the Inrupt eslint config? Or was it primarily to fix the linting error?

Since SolidLabLib is not an Inrupt project, I would be more in favor of keeping the linting rules under a namespace we can easily control. Just in case we quickly need to make changes on something.
And I do have a strong opinion on `'` vs `"` :-)

Also pinging @RubenVerborgh here, as I don't want to claim sole authorship of this project.

**Comment by jeswr** [comment]
Primarily to fix the dependency errors before I created a PR with some functions that are better suited here than in other projects that I'm working on.

I don't care strongly about who owns the configs - but I do think the rushstack technique is very useful in making the configs shareable across repos without handling the dependencies in each one.

**Comment by RubenVerborgh** [comment]
@rubensworks Anything you can do in your package to avoid the manual imports?
The rushtack thing seems helpful indeed.

**Comment by rubensworks** [comment]
> but I do think the rushstack technique is very useful in making the configs shareable across repos without handling the dependencies in each one.

Yes, fully agree!
I guess as long as our configs package correctly lists its dependencies, and we add `require("@rushstack/eslint-patch/modern-module-resolution")` to our eslintrc, this should all work?

**Comment by jeswr** [comment]
Yep 😀 I believe that's what @thisismissem did for the Inrupt configs

**Comment by rubensworks** [comment]
Ok, will look into that today. Thanks for the input!

**Comment by rubensworks** [comment]
Done in #90c87d36988cdf1b5957224cd66a6727e611486a

**Comment by ThisIsMissEm** [comment]
I'd definitely not recommend depending on the Inrupt eslint configuration, it's always subject to change as we evolve how we write tech at Inrupt. But, using `@rushstack` helps significantly with managing shared configurations.

**Pull request closed without merging**
